name: Build sphinx docs

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]

    - name: Build docs
      run: |
        make -C docs/ clean html

    - name: Commit documentation changes
      run: |
        git clone https://github.com/michael-gracie/gslides.git --branch gh-pages --single-branch gh-pages
        rm -rf gh-pages/*
        ls -a gh-pages/
        cp -r docs/_build/html/* gh-pages/
        cd gh-pages
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git add .
        git commit -m "Updated documentation" -a || true
        # The above command will fail if no changes were present, so we ignore
        # the return code.

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.ACTIONS_TOKEN }}
        branch: gh-pages
        directory: gh-pages
